import { IsArray, IsBoolean, IsEnum, IsOptional, IsString, Length, Matches, MaxLength, MinLength } from 'class-validator'
import { ArticleStatus } from './entities'
export class LoginDto { @IsString() username!:string; @IsString() password!:string }
export class BootstrapDto { @IsString() @MinLength(3) username!:string; @IsString() @MinLength(8) password!:string; @IsString() display_name!:string }
export class CreateClientDto { @IsString() @Length(2,120) name!:string; @IsOptional() @IsString() contact_name?:string; @IsOptional() @IsString() contact_phone?:string; @IsString() @MinLength(3) owner_username!:string; @IsString() @MinLength(8) owner_password!:string; @IsString() owner_display_name!:string }
export class CreateSiteDto { @IsString() client_id!:string; @IsString() @Length(2,120) name!:string; @IsString() @Matches(/^[a-zA-Z0-9.-]+$/) domain!:string; @IsString() template_key!:string; @IsString() repository_url!:string; @IsOptional() @IsString() source_branch?:string; @IsOptional() @IsString() publish_branch?:string; @IsOptional() @IsString() template_root?:string; @IsOptional() @IsString() pages_project_name?:string }
export class UpdateSiteDto { @IsOptional() @IsString() @Length(2,120) name?:string; @IsOptional() @IsString() @Matches(/^[a-zA-Z0-9.-]+$/) domain?:string; @IsOptional() @IsString() template_key?:string; @IsOptional() @IsString() repository_url?:string; @IsOptional() @IsString() source_branch?:string; @IsOptional() @IsString() publish_branch?:string; @IsOptional() @IsString() template_root?:string; @IsOptional() @IsString() pages_project_name?:string }
export class CategoryDto { @IsString() @Length(1,80) name!:string; @IsOptional() @IsString() @Matches(/^[a-z0-9]+(?:-[a-z0-9]+)*$/) slug?:string }
export class ArticleDto { @IsOptional() @IsString() external_id?:string; @IsString() @Length(1,200) title!:string; @IsOptional() @IsString() @Matches(/^[a-z0-9]+(?:-[a-z0-9]+)*$/) slug?:string; @IsOptional() @IsString() category_id?:string; @IsOptional() @IsArray() @IsString({each:true}) tags?:string[]; @IsOptional() @IsString() @MaxLength(1000) summary?:string; @IsString() @MaxLength(2000000) content_html!:string; @IsOptional() @IsString() cover_image_url?:string; @IsOptional() @IsString() @MaxLength(200) seo_title?:string; @IsOptional() @IsString() @MaxLength(500) seo_description?:string; @IsEnum(ArticleStatus) status!:ArticleStatus }
export class ExternalWebhookDto { @IsString() sign!:string; @IsOptional() @IsString() class_id?:string; @IsString() title!:string; @IsString() content!:string; @IsOptional() @IsString() author_id?:string; @IsOptional() @IsString() image_url?:string }
