import { Column, CreateDateColumn, Entity, Index, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm'

export enum UserRole { PLATFORM_ADMIN='platform_admin', CLIENT_OWNER='client_owner' }
export enum ArticleStatus { DRAFT='draft', PUBLISHED='published', DELETED='deleted' }
export enum JobStatus { QUEUED='queued', BUILDING='building', PUSHED='pushed', FAILED='failed' }

@Entity('clients') export class Client { @PrimaryGeneratedColumn('uuid') id!:string; @Index({unique:true}) @Column() name!:string; @Column({nullable:true}) contactName?:string; @Column({nullable:true}) contactPhone?:string; @Column({default:true}) active!:boolean; @CreateDateColumn() createdAt!:Date; @UpdateDateColumn() updatedAt!:Date }
@Entity('users') export class User { @PrimaryGeneratedColumn('uuid') id!:string; @Index({unique:true}) @Column() username!:string; @Column() passwordHash!:string; @Column() displayName!:string; @Column({type:'enum',enum:UserRole}) role!:UserRole; @Index() @Column({nullable:true}) clientId?:string; @Column({default:true}) active!:boolean; @Column({type:'timestamptz',nullable:true}) lastLoginAt?:Date; @CreateDateColumn() createdAt!:Date; @UpdateDateColumn() updatedAt!:Date }
@Entity('refresh_tokens') export class RefreshToken { @PrimaryGeneratedColumn('uuid') id!:string; @Index() @Column() userId!:string; @Index({unique:true}) @Column() tokenHash!:string; @Column({type:'timestamptz'}) expiresAt!:Date; @Column({type:'timestamptz',nullable:true}) revokedAt?:Date; @CreateDateColumn() createdAt!:Date }
@Entity('sites') export class Site { @PrimaryGeneratedColumn('uuid') id!:string; @Index() @Column() clientId!:string; @Index({unique:true}) @Column() domain!:string; @Column() name!:string; @Column() templateKey!:string; @Column() repositoryUrl!:string; @Column({default:'master'}) sourceBranch!:string; @Column({default:'publish'}) publishBranch!:string; @Column({default:'.'}) templateRoot!:string; @Column({nullable:true}) pagesProjectName?:string; @Column({default:true}) active!:boolean; @CreateDateColumn() createdAt!:Date; @UpdateDateColumn() updatedAt!:Date }
@Entity('site_credentials') export class SiteCredential { @PrimaryGeneratedColumn('uuid') id!:string; @Index({unique:true}) @Column() keyHash!:string; @Index() @Column() siteId!:string; @Column({default:true}) active!:boolean; @CreateDateColumn() createdAt!:Date; @Column({type:'timestamptz',nullable:true}) revokedAt?:Date }
@Entity('categories') @Index(['siteId','slug'],{unique:true}) export class Category { @PrimaryGeneratedColumn('uuid') id!:string; @Index() @Column() siteId!:string; @Column() name!:string; @Column() slug!:string; @Column({type:'int',default:0}) sortOrder!:number; @CreateDateColumn() createdAt!:Date; @UpdateDateColumn() updatedAt!:Date }
@Entity('articles') @Index(['siteId','externalId'],{unique:true}) @Index(['siteId','slug'],{unique:true}) export class Article { @PrimaryGeneratedColumn('uuid') id!:string; @Index() @Column() siteId!:string; @Column() externalId!:string; @Column() title!:string; @Column() slug!:string; @Index() @Column({nullable:true}) categoryId?:string; @Column({type:'simple-json',nullable:true}) tags?:string[]; @Column({type:'text',default:''}) summary!:string; @Column({type:'text'}) contentHtml!:string; @Column({nullable:true}) coverImageUrl?:string; @Column({nullable:true}) seoTitle?:string; @Column({type:'text',nullable:true}) seoDescription?:string; @Column({type:'enum',enum:ArticleStatus,default:ArticleStatus.DRAFT}) status!:ArticleStatus; @Column({type:'int',default:1}) version!:number; @Column({type:'simple-json',nullable:true}) sourceMeta?:Record<string,string>; @Column({type:'timestamptz',nullable:true}) publishedAt?:Date; @Column({type:'timestamptz',nullable:true}) deletedAt?:Date; @CreateDateColumn() createdAt!:Date; @UpdateDateColumn() updatedAt!:Date }
@Entity('build_jobs') export class BuildJob { @PrimaryGeneratedColumn('uuid') id!:string; @Index() @Column() siteId!:string; @Column({type:'simple-json',default:'[]'}) articleIds!:string[]; @Column({type:'enum',enum:JobStatus,default:JobStatus.QUEUED}) status!:JobStatus; @Column({nullable:true}) gitCommit?:string; @Column({type:'text',nullable:true}) errorMessage?:string; @CreateDateColumn() createdAt!:Date; @UpdateDateColumn() updatedAt!:Date }
