export type User={id:string;display_name:string;role:'platform_admin'|'client_owner';client_id?:string}
export type Site={id:string;name:string;domain:string;clientId:string;templateKey:string;repositoryUrl:string;sourceBranch:string;publishBranch:string;templateRoot:string;pagesProjectName?:string;active:boolean}
export type Category={id:string;name:string;slug:string}
export type Article={id:string;title:string;slug:string;categoryId?:string;tags?:string[];summary:string;contentHtml:string;coverImageUrl?:string;seoTitle?:string;seoDescription?:string;status:'draft'|'published'|'deleted';updatedAt:string}
export type Job={id:string;status:string;createdAt:string;errorMessage?:string}
const base=import.meta.env.VITE_API_BASE_URL||'http://localhost:3003'
let token=localStorage.getItem('publisher-access')||''
export const auth={set(v:string){token=v;localStorage.setItem('publisher-access',v)},clear(){token='';localStorage.removeItem('publisher-access')}}
async function request<T=any>(path:string,init:RequestInit={}){const headers={...(init.body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{}),...(init.headers||{})};const r=await fetch(base+path,{...init,headers});if(!r.ok)throw new Error((await r.json().catch(()=>null))?.message||`请求失败 ${r.status}`);return r.json() as Promise<T>}
async function uploadImage(file:File){const data=new FormData();data.append('file',file);const r=await fetch(`${base}/portal/v1/uploads/images`,{method:'POST',headers:token?{Authorization:`Bearer ${token}`}:undefined,body:data});if(!r.ok)throw new Error('图片上传失败');return r.json() as Promise<{url:string}>}
export const api={login:(username:string,password:string)=>request<{access_token:string;refresh_token:string;user:User}>('/auth/login',{method:'POST',body:JSON.stringify({username,password})}),me:()=>request<User>('/auth/me'),sites:()=>request<Site[]>('/portal/v1/sites'),categories:(siteId:string)=>request<Category[]>(`/portal/v1/sites/${siteId}/categories`),createCategory:(siteId:string,name:string)=>request<Category>(`/portal/v1/sites/${siteId}/categories`,{method:'POST',body:JSON.stringify({name})}),removeCategory:(siteId:string,id:string)=>request(`/portal/v1/sites/${siteId}/categories/${id}`,{method:'DELETE'}),articles:(siteId:string,status='')=>request<Article[]>(`/portal/v1/sites/${siteId}/articles${status?`?status=${status}`:''}`),jobs:(siteId:string)=>request<Job[]>(`/portal/v1/sites/${siteId}/jobs`),createArticle:(siteId:string,body:unknown)=>request(`/portal/v1/sites/${siteId}/articles`,{method:'POST',body:JSON.stringify(body)}),updateArticle:(siteId:string,id:string,body:unknown)=>request(`/portal/v1/sites/${siteId}/articles/${id}`,{method:'PUT',body:JSON.stringify(body)}),removeArticle:(siteId:string,id:string)=>request(`/portal/v1/sites/${siteId}/articles/${id}`,{method:'DELETE'}),restoreArticle:(siteId:string,id:string)=>request(`/portal/v1/sites/${siteId}/articles/${id}/restore`,{method:'POST'}),uploadImage,adminDashboard:()=>request('/admin/v1/dashboard'),adminClients:()=>request<any[]>('/admin/v1/clients'),createClient:(body:unknown)=>request('/admin/v1/clients',{method:'POST',body:JSON.stringify(body)}),createSite:(body:unknown)=>request<{site_id:string;api_key:string}>('/admin/v1/sites',{method:'POST',body:JSON.stringify(body)}),updateSite:(id:string,body:unknown)=>request<Site>(`/admin/v1/sites/${id}`,{method:'PUT',body:JSON.stringify(body)})}
